[package]
name = "region_cache_memory_engine"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
testexport = []

[dependencies]
crossbeam-epoch = "0.9"
crossbeam-utils = "0.8"
scopeguard = {version = "1.1.0", default-features = false}
engine_traits = { workspace = true }
collections = { workspace = true }
bytes = "1.0"
crossbeam = "0.8"
tikv_util = { workspace = true }
txn_types = { workspace = true }
log_wrappers = { workspace = true }
slog-global = { workspace = true }
slog = { workspace = true }
engine_rocks = { workspace = true }
fail = "0.5"
kvproto = { workspace = true }
yatp = { workspace = true }
lazy_static = "1.3"
prometheus = { version = "0.13", features = ["nightly"] }
prometheus-static-metric = "0.5"

[dev-dependencies]
keys = { workspace = true }
tempfile = "3.0"
proptest = "1.0.0"
rand = "0.8.0"
