[package]
name = "keys"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
byteorder = "1.2"
kvproto = { git = "https://github.com/SpadeA-Tang/kvproto.git", branch = "issue-11976-bucket" }
log_wrappers = { path = "../log_wrappers" }
thiserror = "1.0"
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util", default-features = false }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
