[package]
name = "skiplist"
version = "0.0.1"
authors = ["The TiKV Authors"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bytes = "1.0"
rand = "0.8.4"
engine_traits = { workspace = true }
crossbeam-skiplist = "0.1.1"
collections = { workspace = true }
txn_types = { workspace = true }
keys = { workspace = true }
yatp = { workspace = true }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
